### ISSUE TITLE
Change 'type' name, related to NodePort, ClusterIP, LoadBalancer, ExternalName to `expose`.

### ISSUE THREAD

**Issue by cdrage** [kedgeproject/kedge#103]
First, I *love* the examples we have, they're great, but one thing kept on sticking out to me and confused me, and that's `type`, which has no indication on what it actually is!

In Kubernetes, there are four different way to publish services, they are:

- ClusterIP
- NodePort
- LoadBalancer
- ExternalName

I propose a different way of exposing each container.

Maybe to possibly another name and key.

`type` -> `expose`

`type: ClusterIP` -> `expose: public`
`type: NodePort` -> `expose: node`
`type: LoadBalancer` -> `expose: balancer`
`type: ExternalName` -> `expose: domain`

To possibly something like this:

```yaml
name: httpd
containers:
- image: centos/httpd
services:
  - name: httpd
    expose: public
    # expose: node
    # expose: balancer
    # optionally a domain
    # - expose: domain
    #     name: foobar.com
    ports:
    - port: 8080
      targetPort: 80
```

Thoughts? Seems cleaner IMO.

ping @kedgeproject/maintainers
