### ISSUE TITLE
Implement StatefulSets

### ISSUE THREAD

**Issue by cdrage** [kedgeproject/kedge#110]
Similar to #52 and covering part of #101 this is an issue in regards to implementing StatefulSets (previously known as PetSets).

We should discuss what form of syntax we will use with Kedge. 

A good start is by looking at the example on https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/

```yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: nginx
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: web
spec:
  serviceName: "nginx"
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: gcr.io/google_containers/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
      annotations:
        volume.beta.kubernetes.io/storage-class: anything
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
```

and on how we can convert it to the "kedge" equivalent.

**Comment by cdrage** [comment]
Of course, here is a list of limitations for StatefulSets (paste from the website):

StatefulSet is a beta resource, not available in any Kubernetes release prior to 1.5.
As with all alpha/beta resources, you can disable StatefulSet through the --runtime-config option passed to the apiserver.
The storage for a given Pod must either be provisioned by a PersistentVolume Provisioner based on the requested storage class, or pre-provisioned by an admin.
Deleting and/or scaling a StatefulSet down will not delete the volumes associated with the StatefulSet. This is done to ensure data safety, which is generally more valuable than an automatic purge of all related StatefulSet resources.
StatefulSets currently require a Headless Service to be responsible for the network identity of the Pods. You are responsible for creating this Service.

**Comment by cdrage** [comment]
Of course there'll be some discussion, but I propose we simply add a `set` key to the root.

Example:

```yaml
name: httpd                                                                                                                                                                                                                                                                       
set: stateful                                                                                                                                                                                                                                                                     
replicas: 3                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                  
containers:                                                                                                                                                                                                                                                                       
  - image: gcr.io/google_containers/nginx-slim:0.8                                                                                                                                                                                                                                
    volumeMounts:                                                                                                                                                                                                                                                                 
    - name: www                                                                                                                                                                                                                                                                   
      mountPath: /usr/share/nginx/html                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                  
services:                                                                                                                                                                                                                                                                         
  - name: nginx                                                                                                                                                                                                                                                                   
    type: NodePort                                                                                                                                                                                                                                                                
    ports:                                                                                                                                                                                                                                                                        
    - port: 8080                                                                                                                                                                                                                                                                  
      targetPort: 80                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                  
persistentVolumes:                                                                                                                                                                                                                                                                
- name: www                                                                                                                                                                                                                                                                       
  size: 1Gi 
```

Thus we can also do:

```yaml
set: daemon
...
```

```yaml
set: replica
...
```

```yaml
set: pet # same thing as stateful
...
```

**Comment by surajssd** [comment]
I had similar idea for supporting multiple controllers with kedge.


But the key that I had in mind was taken from Kubernetes terminology:

```
controller: deployment
```

```
controller: job
```

```
controller: daemonset
```

>Another thing to note is once we have labels/annotations are implented (I believe they're not yet?) we can cover:

We do support `labels` but we don't support `annotations` yet, because with `annotations` we are not sure where to put what `annotations` and with different resources in kubernetes it will change. If you are targeting `annotations` just for using `storage-class` or Dyanmic volume provisioner, then we don't need to rely on `annotations` because it is a field in `PersistentVolumeClaimSpec` called `storageClassName` see [this](https://kubernetes.io/docs/api-reference/v1.6/#persistentvolumeclaimspec-v1-core).


But the problem is that now we have `podSpec` and `deploymentSpec` merged into `appSpec` so that might be a problem since `StatefulSet` will have it's own things of spec level fields, which are not similar to `deploymentSpec`.

I think this point was brought up before, with `kedge` we have removed the problem of leaky abstraction at `pod` level by directly using `podspec`, now how do we deal with the leaky abstraction at the controller level. Or to put it in other words how do we add support for controller specific fields without ignoring anything.

**Comment by containscafeine** [comment]
@kadel and I had a very similar discussion when talking about implementing Jobs (#52), but we felt that defining a solo file for just a job does not make sense, and it makes sense for jobs to be defined with the `app` part, however since both contain PodSpec, it was tempting to merge it with the App struct and specify a controller which says `kind: job`, `kind: deployment` to define the behavior of the written spec.

An alternate way could be have separate field name for each controller -
```yaml
deployment:
- name: app1
  ...
- name: app2
  ...

statefulSet:
- name: ss1
  ...
- name: ss2
  ...

jobs:
- name: job1
  ...
- name: job2
  ...
```

**Comment by cdrage** [comment]
@containscafeine I like your implementation, having a separate field name / key for each controller. But this brings up problems with the "containers" category. By design, we're having each file (db, web) as a separate file / section all with their own separate "containers" category. I wish we could have it like this:

```yaml
deployment:
 containers:
 ...
etc.
```

I do like your design however, but we would *still* have to create separate files as if you have both a `statefulSet` and `jobs`, they'll BOTH use the same containers.

**Comment by pradeepto** [comment]
@containscafeine I am confused here:

An alternate way could be have separate field name for each controller -
```yaml
deployment:
- name: app1
  ...
- name: app2
  ...
```
Is that supposed to be in a single file? If so, how do we define the same thing in one app/service per file?

**Comment by containscafeine** [comment]
@cdrage @pradeepto not very sure about this because, yes, it does allow specifying multiple apps in one file by introducing a level and goes against the single file approach, while with jobs, we are able to define multiple jobs in one file.
Would love @kadel's thoughts on this!

**Comment by cdrage** [comment]
@containscafeine 

problem is that there is no use-case for this. I doubt anyone would like to deploy both a daemonset / stateful set with the exact same containers as each-other... That's the main issue that's occurring here. Having different names as the root keys (deployment, statefulSet, etc.) wouldn't be viable with multi-container deployments.

**Comment by containscafeine** [comment]
@cdrage oh, you're talking about not making it a list and being able to define only one definition under one controller. I'm fine with that :)

**Comment by cdrage** [comment]
@containscafeine For the most part, yes! :+1:

**Comment by containscafeine** [comment]
ongoing discussions at #119

**Comment by surajssd** [comment]
As discussed in here https://github.com/kedgeproject/kedge/issues/110#issuecomment-313016324

there are two approaches here either add a root level key for each controller:

### First approach

for deployment:
```yaml
deployment:
  containers:
  - image: centos/httpd
```

for job
```yaml
job:
  containers:
  - image: gitcrawler
```

**vs**

### Second approach

for deployment:

```yaml
containers:
- image: centos/httpd
```

for job:

```yaml
kind: job
containers:
- image: gitcrawler
```

Speaking for myself I am inclined towards the second approach. Because it is less indentation, also if user does not provide the `kind` field then we can always default to `deployment`, with first approach this default won't be possible.

Also in second approach we can do something similar to how kubernetes does the detection based on the kind field. So that we don't need to populate the app struct with everything, it will rather be a clean segregated structs depending on the kind everything will be happening.
