### ISSUE TITLE
Allow adding Kubernetes artifacts to Kedge file.

### ISSUE THREAD

**Issue by kadel** [kedgeproject/kedge#157]
It should be possible to add ordinary Kubernetes object to Kedge yaml file.

This will allow extending Kedge YAML  files with any Kubernetes object regardless if we add explicit support for it or not.

Implementation:

Add new top level key that contains list of kubernetes objects.
Lets call it `extras` for now as I can't think of proper name :smile: 

example
```yaml
name: httpd
containers:
- image: centos/httpd
services:
  - name: httpd
    type: NodePort
    ports:
    - port: 8080
      targetPort: 80
extras:
  - apiVersion: batch/v2alpha1
    kind: CronJob
    metadata:
      name: hello
    spec:
      schedule: "*/1 * * * *"
      jobTemplate:
        spec:
          template:
            spec:
              containers:
              - name: hello
                image: busybox
                args:
                - /bin/sh
                - -c
                - date; echo Hello from the Kubernetes cluster
              restartPolicy: OnFailure
```

**Comment by cdrage** [comment]
@kadel I like this... However... With further discussion in #116 wouldn't our current implementation be "too close" to what we can simply provide in `extras`? For example:

```yaml
  template:
    metadata:
      name: pi
    spec:
      containers:
      - name: pi
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
      activeDeadlineSeconds: 1
```

Don't mind me in-case this is for a separate discussion :+1:

**Comment by containscafeine** [comment]
@kadel +1 to the idea, but instead of adding a new root level field, can we just start accepting Kubernetes artifacts?
So,
file1.yml -
```yaml
name: httpd
containers:
- image: centos/httpd
services:
  - name: httpd
    type: NodePort
    ports:
    - port: 8080
      targetPort: 80
```

file2.yml -
```yaml
apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
```

So, if someone wants to do one file, then we have `---` separator anyway,

**Comment by kadel** [comment]
I'm looking at `---` separator as a way to put multiple applications into a single file.
`---` is separating applications.

What if you want to add something that logically belongs to a single app? It should be in the same file / section

One application as I look at it is usually one Deployment, one or multiple  Services and additional support objects like Jobs and other extras and all this should be in a single file or single section.

**Comment by containscafeine** [comment]
@kadel About the UX, if someone wants to put in their Kubernetes resource, they should just be able to copy and paste it and it should work. Increasing a level of indentation will mess that up.

`---` can be used in this case IMO!

Is there some way we can do it at the root level?

**Comment by kadel** [comment]
> --- can be used in this case IMO!

It will illogically separate one application into multiple files / sections. 

IMHO it's completely OK to have it "one level deep" Not every application will use it. It will be used only for more complicated or less common things.

**Comment by surajssd** [comment]
My simple idea for doing this both on the user side and the implementation wise is that anything we cannot parse fairly is k8s artifact and anything we can parse is kedge.

So for example people can give a k8s artifact directly and since we know this does not look like kedge we feed the entire thing to `kubectl`. So with this we don't need to add extra level of indentation and also creates separation of concerns.

For example:

## e.g. 1

`app.yaml` (kedge)

```yaml
name: redis
containers:
...
```

`secret.yaml` (pure k8s)

```yaml
apiVersion: v1
kind: Secret
metadata:
...
```

Here user has defined kedge apps and also using the off the shelf resources that can be deployed directly to k8s.

So before introducing secret user was doing:

```bash
kedge create -f app.yaml
```

with addition of secrets user is now doing:

```bash
kedge create -f app.yaml -f secret.yaml
```

No change is needed to the config no extra copying, no need to deal with indentation.

## e.g. 2

`app.yaml` (kedge and k8s)

```yaml
name: redis
containers:
- image: redis
---
apiVersion: v1
kind: Secret
metadata:
...
```

Here user has put both the configs in one file because she cares about it having to be together. This will be intuitive without introduction of `extra` (pun intended ;) ) field.

Here user keeps doing:

```bash
kedge create -f app.yaml
```


This approach might not make our(kedge developers) life easier with all the detection of k8s vs kedge but is very simple approach and also as @containscafeine  said anyone can either copy paste without having to deal with the indentation or simple use the file directly with kedge.

**Comment by kadel** [comment]
I see your point, but I still think that it will be better to do it without using document separator (`---`)

One file (one yaml document) should represent one application as a whole. This breaks this  idea.

**Comment by surajssd** [comment]
@kadel yes folks can still do the **one file one app way**, that is what I showed in example no 1 in https://github.com/kedgeproject/kedge/issues/157#issuecomment-315958508

**Comment by surajssd** [comment]
### `extras` vs `---`

#### with `extras`

```yaml
name: httpd
containers:
- image: centos/httpd
extras:
- apiVersion: batch/v2alpha1
  kind: CronJob
  metadata:
    name: hello
  spec:
    schedule: "*/1 * * * *"
    jobTemplate:
      spec:
        template:
          spec:
            containers:
            - name: hello
              image: busybox
              args:
              - /bin/sh
              - -c
              - date; echo Hello from the Kubernetes cluster
            restartPolicy: OnFailure
```

#### with `---`

```yaml
name: httpd
containers:
- image: centos/httpd

---
apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
```

What is the problem of doing it in second approach as opposed to the first one?
In second approach there is less indentation, also i can just add three dashes and paste the file, no need of indentation.
