### ISSUE TITLE
Find a better convention referencing env vars in container spec

### ISSUE THREAD

**Issue by containscafeine** [kedgeproject/kedge#16]
The current way of referencing other sources for environment variables is like the following -

```yaml
name: web
replicas: 1
containers:
- image: wordpress:4
  env:
  - name: WORDPRESS_DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: wordpress
        key: DB_PASSWD
  - name: WORDPRESS_DB_NAME
    valueFrom:
      configMapKeyRef:
        key: MYSQL_DATABASE
        name: database
```

We can establish a convention and replace this with -

```yaml
name: web
replicas: 1
containers:
- image: wordpress:4
  env:
  - name: WORDPRESS_DB_PASSWORD
    secretRef: wordpress/DB_PASSWD
  - name: WORDPRESS_DB_NAME
    configMapRef: MYSQL_DATABASE/database
```

To include all data from a given secret/configMap -

```yaml
name: web
replicas: 1containers:
- image: wordpress:4
  env:
  - name: WORDPRESS_DB_PASSWORD
    secretRef: wordpress/DB_PASSWD
  - name: WORDPRESS_DB_NAME
    configMapRef: MYSQL_DATABASE/database
  - secretRef: secret-certs
```
