### ISSUE TITLE
kedge does not fail when extra fields specified

### ISSUE THREAD

**Issue by containscafeine** [kedgeproject/kedge#168]
I have an extra field in my kedge definition -

```yaml
name: httpd
batman: true              # extra field
containers:
- image: centos/httpd
services:
  - name: httpd
    type: NodePort
    ports:
    - port: 8080
      targetPort: 80
```
Running `kedge generate` on this file does not fail and simply ignores the extra field, while it should have failed saying something like `unknown field 'batman' passed as input`

This creates a lot of room for error since a simple spelling mistake in the spec will render the generated artifacts useless and the user will never get to know about it.
