### ISSUE TITLE
kedge init

### ISSUE THREAD

**Issue by kadel** [kedgeproject/kedge#215]
We need to make it easier for users to bootstrap new Kedge files.

One idea might be to have `kedge init` command.

example of the use
`kedge init -f kedge.yml  --name asdf  --image foo/bar --port 80`  

it will create following `kedge.yml` file
```yaml
name: asdf
containers:
  - image: foo/bar
services:
  - ports:
    - port: 80
```

**Comment by surajssd** [comment]
The idea of `init` SGTM, but I think having it in interactive would be more fun and easier than flags?

Like `glide` does it?

**Comment by kadel** [comment]
I think that if there are only three flags/questions it is better to have just flags. There is no benefit having an interactive mode with three questions.

Only once we start adding more flags and this command is proven to be useful, we can add interactive mode, but right now it's not worth the effort. Let's try to do simple things right first.

**Comment by cdrage** [comment]
One tool that does this well is Nomad with their `nomad init`: https://www.nomadproject.io/docs/commands/init.html

Although it's just boiler-plate code.

I do like the idea however for using `kedge init` and passing in variables such as the image, etc. Although this would only work with setting up a basic example.. Although this is expanding on it, perhaps a command called `kedge append` would be beneficial too (in the future perhaps?). `kedge init` to deploy the initial file, `kedge append` to add to it. For example: `kedge append -f kedge.yaml --name asdf --image bar/foo --port 80` would add to the current `kedge init` and create:

```yaml
name: asdf
containers:
  - image: foo/bar
  - image: bar/foo
services:
  - ports:
    - port: 80
    - port: 81
```

of if supplied with a different name: `kedge append -f kedge.yaml --name nginx --image nginx --port 8080`

would append/create:

```yaml
name: asdf
containers:
  - image: foo/bar
  - image: bar/foo
services:
  - ports:
    - port: 80
    - port: 81
---
name: nginx
containers:
  - image: nginx
services:
  - ports:
    - port: 8080
```
