### ISSUE TITLE
shortcut for port

### ISSUE THREAD

**Issue by kadel** [kedgeproject/kedge#216]
Most of the application expose at least one port. Exposing just one
port requires 2 indentations levels and 3 lines. Some shortcut for this would be nice.

**Comment by pradeepto** [comment]
I think this is important enough to be added to 0.2.0 milestone. WDYT @kadel ?

**Comment by containscafeine** [comment]
+1

How about -
```yaml
name: httpd
containers:
- image: centos/httpd
services:
  - name: httpd
    ports:
    - port: 8080
      targetPort: 80
      protocol: UDP
```
can be replaced by -
```yaml
name: httpd
containers:
- image: centos/httpd
services:
  - name: httpd
    portMapping: 8080:80/UDP        # port:targetPort/protocol
```
where in portMapping, port is required, targetPort is optional, protocol is optional

**Comment by kadel** [comment]
One service can have multiple ports so it should be some kind of array

**Comment by containscafeine** [comment]
@kadel makes sense, how about -
```yaml
name: httpd
containers:
- image: centos/httpd
services:
  - name: httpd
    portMapping:
    - 8080:80/UDP        # port:targetPort/protocol
```
