### ISSUE TITLE
kedge append

### ISSUE THREAD

**Issue by surajssd** [kedgeproject/kedge#221]
Once we implement `kedge init` we can think of adding support for `kedge append` which takes data from cmdline and adds it to the file, without someone having to edit file manually.

In @cdrage's own words

---

One tool that does this well is Nomad with their `nomad init`: https://www.nomadproject.io/docs/commands/init.html

Although it's just boiler-plate code.

I do like the idea however for using `kedge init` and passing in variables such as the image, etc. Although this would only work with setting up a basic example.. Although this is expanding on it, perhaps a command called `kedge append` would be beneficial too (in the future perhaps?). `kedge init` to deploy the initial file, `kedge append` to add to it. For example: `kedge append -f kedge.yaml --name asdf --image bar/foo --port 80` would add to the current `kedge init` and create:

```yaml
name: asdf
containers:
  - image: foo/bar
  - image: bar/foo
services:
  - ports:
    - port: 80
    - port: 81
```

of if supplied with a different name: `kedge append -f kedge.yaml --name nginx --image nginx --port 8080`

would append/create:

```yaml
name: asdf
containers:
  - image: foo/bar
  - image: bar/foo
services:
  - ports:
    - port: 80
    - port: 81
---
name: nginx
containers:
  - image: nginx
services:
  - ports:
    - port: 8080
```

---

Taken from https://github.com/kedgeproject/kedge/issues/215#issuecomment-321571594 more discussion at https://github.com/kedgeproject/kedge/issues/215#issuecomment-321571594

We can only think about this once https://github.com/kedgeproject/kedge/issues/215 is implemented. So right now this is blocked on https://github.com/kedgeproject/kedge/issues/215
