### ISSUE TITLE
version numbers / image tags in kedge YAML

### ISSUE THREAD

**Issue by jstrachan** [kedgeproject/kedge#224]
whats the current approach for replacing version numbers in a kedge YAML? Am thinking of CI / CD pipelines that tend to generate new unique release numbers for each new version and tend to put those versions in the YAML as a version label and then use the docker image tag of the same name as the version

should we use environment variable expressions or something? e.g.

```yaml
name: foo
labels:
  version: "${VERSION}"
image: "foo/bar:${VERSION}"
```
then we can specify it via something like...
```
export VERSION="1.2.3"
kedge create -f foo.yaml (or whatever the command is ;)
```
