### ISSUE TITLE
Add annotations support

### ISSUE THREAD

**Issue by containscafeine** [kedgeproject/kedge#262]
While trying to define an application manifest (Eclipse Che) using Kedge, I'm needing to add annotations to the Deployment, and at other sub levels.

The entire deployment file can be found at https://github.com/containscafeine/kedge-fabric8-platform/blob/master/fabric8/kubernetes/che-starter-deployment.yml

Related piece is -

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    fabric8.io/git-commit: 2ebbe3448c2a1fd5c903badd7a8b264253f39124
    fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=che-starter&var-version=4.0-SNAPSHOT
    fabric8.io/scm-con-url: scm:git:git@github.com:fabric8io/fabric8-platform.git/apps/che-starter
    fabric8.io/scm-url: http://github.com/fabric8io/fabric8-platform/apps/che-starter
    fabric8.io/git-branch: master
    fabric8.io/scm-devcon-url: scm:git:git@github.com:fabric8io/fabric8-platform.git/apps/che-starter
    fabric8.io/scm-tag: app-console-2.0.1
  labels:
    app: che-starter
    provider: fabric8
    version: 4.0-SNAPSHOT
    group: io.fabric8.platform.apps
  name: che-starter
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: che-starter
      provider: fabric8
      group: io.fabric8.platform.apps
  template:
    metadata:
      annotations:
        fabric8.io/git-commit: 2ebbe3448c2a1fd5c903badd7a8b264253f39124
        fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=che-starter&var-version=4.0-SNAPSHOT
        fabric8.io/scm-con-url: scm:git:git@github.com:fabric8io/fabric8-platform.git/apps/che-starter
        fabric8.io/scm-url: http://github.com/fabric8io/fabric8-platform/apps/che-starter
        fabric8.io/git-branch: master
        fabric8.io/scm-devcon-url: scm:git:git@github.com:fabric8io/fabric8-platform.git/apps/che-starter
        fabric8.io/scm-tag: app-console-2.0.1
        maven.fabric8.io/source-url: jar:file:/home/concaf/fabric8/src/github.com/fabric8io/fabric8-platform/apps/che-starter/target/che-starter-4.0-SNAPSHOT.jar!/META-INF/fabric8/kubernetes.yml
      labels:
        app: che-starter
        provider: fabric8
        version: 4.0-SNAPSHOT
        group: io.fabric8.platform.apps
    spec:
...
...
```

With our current implementation, we cannot add annotations, and I think we should.

This has been discussed before at https://github.com/kedgeproject/kedge/issues/110#issuecomment-313016324 but never materialized.

**Comment by containscafeine** [comment]
This also opens up a broader discussion about supporting `ObjectMeta`. There are multiple fields like `DeletionGracePeriodSeconds` or `ClusterName` and plenty more which we do not support and could be limiting for an end user.
Does it make sense to merge `ObjectMeta` with the Controller or make it a part of `ControllerFields` (like we merge PodSpec and ControllerSpec` and bring everything at the same level.
Is that limiting in some way?

**Comment by kadel** [comment]
We already handle labels. Annotations should be done in the same way.

**Comment by containscafeine** [comment]
I'll try merging ObjectMeta with ControllerSpec and see if we hit any issues. If not, maybe we can proceed that way.

**Comment by containscafeine** [comment]
@kadel I've started work on this in #267.
So, nothing conflicted when I added ObjectMeta to ControllerFields and removed Name and Labels since those are covered in ObjectMeta.

How do we want to do this?
Do we want to add support only at the top level with the controller, or at every level where specs are merged?

And is it a good idea to trickle down the annotations defined at the root level to every resource that's created?

**Comment by containscafeine** [comment]
gentle ping @kadel @surajssd

**Comment by kadel** [comment]
> And is it a good idea to trickle down the annotations defined at the root level to every resource that's created?

I think it should have the same rules as names.
If there is no labels or annotations specified, then the top level one should be used.

**Comment by containscafeine** [comment]
```
[3:26 PM] 
ping @tkral, around?


[5:00 PM] 
tkral
@concaf hi


[5:01 PM] 
concaf @tkral I was continuing on https://github.com/kedgeproject/kedge/issues/262
GitHub
Add annotations support · Issue #262 · kedgeproject/kedge
While trying to define an application manifest (Eclipse Che) using Kedge, I'm needing to add annotations to the Deployment, and at other sub levels. The entire deployment file can be found at https...
 


[5:01 PM] 
I am a bit confused on how to proceed for other Kubernetes resources


[5:02 PM] 
tkral what other resources?


[5:02 PM] 
concaf e.g. if someone has specified labels, annotations, name, namespace and DeletionGracePeriodSeconds


[5:02 PM] 
at the root level of their kedge


[5:02 PM] 
this will go into ObjectMeta


[5:03 PM] 
so, we want to set the same ObjectMeta for the services, ingresses, etc defined in the same file?


[5:03 PM] 
tkral
not exactly the same


[5:03 PM] 
you should merge annotations and labels with exiting ones for given resource


[5:04 PM] 
concaf what do we gain by merging them?


[5:05 PM] 
I mean, annotations can also be set for certain resources like setting initContainers using annotations, now, if we set that annotation for every Kubernetes resource that we generate, does it make sense?


[5:05 PM] 
tkral
I think we are talking about something else


[5:06 PM] 
it definetly makes sense to set the same annotation for every object we generate


[5:06 PM] 
let me show it on example


[5:06 PM] 
concaf sure


[5:07 PM] 
tkral
we are already doing that for labels


[5:08 PM] 
and we should do the same for annotations


[5:08 PM] 
```


[5:08 PM] 
 ```yaml
name: httpd
containers:
- image: centos/httpd
labels:
  foo: bar

  
services:
  - name: httpd
    type: NodePort
    ports:
    - port: 8080
      targetPort: 80

```


[5:08 PM] 
this will create deployment with label foo: bar and also service with the same label


[5:09 PM] 
annotations should do the same


[5:09 PM] 
concaf @tkral yeah, but why do we need to set it for every generated Kubernetes resource?


[5:09 PM] 
tkral why not? :smile:


[5:09 PM] 
concaf :stuck_out_tongue:


[5:10 PM] 
So, maybe the user wants to set labels only for one thing


[5:10 PM] 
tkral
yep, and than we should merge it


[5:10 PM] 
concaf not for all the resources


[5:10 PM] 
okay, so how does user set one annotation only for a deployment, and not for a service?


[5:11 PM] 
or a label?


[5:11 PM] 
tkral
Until we hav that use case i wouldn't worry about it


[5:11 PM] 
that is easy


[5:11 PM] 
concaf
```annotations:
    pod.beta.kubernetes.io/init-containers: '[
        {
            "name": "init-myservice",
            "image": "busybox",
            "command": ["sh", "-c", "until nslookup myservice; do echo waiting for myservice; sleep 2; done;"]
        },
```
(edited)
1 reply 1 day ago View thread

[5:11 PM] 
tkral
```yaml
name: httpd
containers:
- image: centos/httpd
labels:  
services:
  - name: httpd
    labels:
       foo: bar
    type: NodePort
    ports:
    - port: 8080
      targetPort: 80
```


[5:12 PM] 
^ this will set label only for serice but not for deployment


[5:12 PM] 
similary the other way around


[5:13 PM] 
concaf





What if someone wants to define init containers using annotations?


[5:13 PM] 
tkral init-container annotations are set on pod level right?


[5:14 PM] 
that is easy :wink:


[5:14 PM] 
concaf :stuck_out_tongue: wrong example


[5:14 PM] 
give me a second


[5:17 PM] 
tkral kedge with initcontainer, that is working alrady working in the current version

````
name: httpd
template:
  metadata:
    annotations:
        pod.beta.kubernetes.io/init-containers: adsf
  spec:
    containers:
      - image: centos/httpd
```


[5:26 PM] 
concaf @tkral the point is, how does a user specify a label only for a deployment?


[5:26 PM] 
let's say I want to label my deployment as "kind: deployment", and I do not to propagate this label to all the other resources in my kedge file, then how do I do that?


[5:27 PM] 
I mean, we should not be auto injecting user specified data to all resources when the user did not intend to.


[5:27 PM] 
Does that make sense?


[5:33 PM] 
tkral
I think it is ok to autoinject them if it is set on root level


[5:34 PM] 
there are only two options, do the propagation, or don't


[5:34 PM] 
that we don't have to propagate it (edited)


[5:36 PM] 
if you think it is better


[5:36 PM] 
but we are alrady doing it for labels


[5:36 PM] 
concaf @tkral so do we propagate only labels and annotations, or the entire ObjectMeta to all generated resources?


[5:37 PM] 
tkral
we can't overwrite it


[5:37 PM] 
if we do propagation that it has to do merge


[5:37 PM] 
what else is there in meta other than name, labels and annotation?


[5:39 PM] 
i know there is more, but most of the stuff are generated by server when object is created no?


[5:41 PM] 
Or we can start without doing any annotations, just adding ObjectMeta to all objects, than we can figure out later what we want to do (edited)


[5:50 PM] 
concaf @tkral we have stuff like DeletionGracePeriodSeconds


[5:50 PM] 
and other specific things that generally people don't use


[5:51 PM] 
@tkral does it make sense only to propagate labels, and not annotations?


[5:52 PM] 
tkral
no


[5:52 PM] 
labels, and annotations should be treated the same way


[5:52 PM] 
concaf okay


[5:52 PM] 
tkral why would you like to do it?


[5:52 PM] 
concaf So at every stage, we can merge labels and annotations from the controller's ObjectMeta, nothing else


[5:53 PM] 
and the values specified in the resource's ObjectMeta takes priority over the controller's ObjectMeta


[5:54 PM] 
tkral
more and more I'm thinking about this we need really simple rule for it


[5:54 PM] 
concaf yeah, agree (edited)


[5:54 PM] 
tkral
If we want to add ObjectMeta to every object, we should start with that


[5:56 PM] 
concaf @tkral yep


[5:57 PM] 
@tkral so, we add ObjectMeta to every object, and the labels and annotations from the controller's ObjectMeta get merged and propagated to all the generated resources


[5:57 PM] 
does that sound good?


[5:58 PM] 
tkral
yep


[5:58 PM] 
do you want propagate everyting, or just labels and annotations?


[5:59 PM] 
concaf @tkral I think just labels and annotations, rest everything does not make sense maybe, there is `name`, `clusterName`, `DeletionGracePeriodSeconds` which can be controller specific


[5:59 PM] 
and many more fields


[6:00 PM] 
we might face issues somewhere maybe


[6:00 PM] 
tkral ok


[6:01 PM] 
sorry, but more and more i'm thinking about it, lets skip propagation for now


[6:02 PM] 
concaf :slightly_smiling_face: @tkral I actually agree with no propagation tbh


[6:02 PM] 
except maybe the app name


[6:02 PM] 
which is not propagation anyway


[6:03 PM] 
tkral
we can add some labels automaticaly to every object (like app:name)


[6:04 PM] 
I originally wanted propagation for this, but than I realized that Kedge can add some labels automatically, without user specifying it.


[6:04 PM] 
Ok, than lets skip propagation now, we can add it later


[6:11 PM] 
concaf ack
```
