### ISSUE TITLE
Auto Populate the popular health checks

### ISSUE THREAD

**Issue by surajssd** [kedgeproject/kedge#285]
## Problem statement

Devs won't care much of Health checks, but it is a good practise for hassle free application deployment.

## What should we do?

Auto populate the readinessProbe and livenessProbe.

## How should we do it?

Most popular applications are exposed on well known ports. In kedge we maintain a mapping of port against livenessProbe and readinessProbe. So we read what port the service is exposed on and we compare that port against our internal mapping, if there exist a mapping and user has not provided a health check of any form we do it for them. But if a user has written liveness or readiness by themselves we should not care to do it for them.

The mapping could look like this:

```
5432:

        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - exec pg_isready 
          initialDelaySeconds: 60
          timeoutSeconds: 5
          failureThreshold: 6
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - exec pg_isready 
          initialDelaySeconds: 5
          timeoutSeconds: 3
          periodSeconds: 5
```

and 

```
6379:

        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          timeoutSeconds: 1
```
and so on ...

Like the above (above health info was taken from Helm charts repo https://github.com/kubernetes/charts).

Also apart from using such a mapping we can just do, other defaults of livenessProbe atleast, suppose a port exposed is 8080 we create a livenessProbe of type `tcpSocket`. 

```
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 1
```

The other values we can keep as defaults or set some standard value that we agree upon.
