### ISSUE TITLE
`kedge build` subcommand which is alias to docker build

### ISSUE THREAD

**Issue by surajssd** [kedgeproject/kedge#287]
We can have something like this:

```
image: <name to give to image>
build:
  local:
    context: <path to a directory containing a Dockerfile>
    Dockerfile: <alternate dockerfile>
```
For starters we are doing local build and push like @cdrage has implemented in kompose

Attempts to solve one specific use case mentioned in https://github.com/kedgeproject/kedge/issues/273

@kedgeproject/maintainers need your opinions here
