### ISSUE TITLE
imagePullSecrets are dropped on the floor

### ISSUE THREAD

**Issue by snoby** [kedgeproject/kedge#304]
While generating a template that used imagePullSecrets I determined that the kedge templating engine drops the "imagePullSecrets" on the floor and doesn't bring them over to the final rendered output.
The debug output is of very little use
the template:
```
name: sparky
labels:
  app: sparky
replicas: 1
containers:
- name: sparky
  image: sparkb/sparky:UNKNOWN_VERSION
  imagePullSecrets:
    - name: dockerhub-key
  livenessProbe:
    httpGet:
      path: /liveness
      port: 10009
  readinessProbe:
    httpGet:
      path: /ready
      port: 10009
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 300m
      memory: 128Mi
```
the output result:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: sparky
  name: sparky
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sparky
      name: sparky
    spec:
      containers:
      - image: sparkbo/sparky:UNKNOWN_VERSION
        livenessProbe:
          httpGet:
            path: /liveness
            port: 10009
        name: sparky
        readinessProbe:
          httpGet:
            path: /ready
            port: 10009
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 300m
            memory: 128Mi
status: {}
```

This along with the lack of passing annotations limits the effectiveness of this potentially wonderful tool!

**Comment by surajssd** [comment]
@snoby thanks for trying out kedge.

`imagePullSecrets` is a pod level field, not a container level field. So please modify the yaml to look like this:

```yaml
name: sparky
labels:
  app: sparky
replicas: 1
containers:
- name: sparky
  image: sparkb/sparky:UNKNOWN_VERSION
  livenessProbe:
    httpGet:
      path: /liveness
      port: 10009
  readinessProbe:
    httpGet:
      path: /ready
      port: 10009
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 300m
      memory: 128Mi
imagePullSecrets:
- name: dockerhub-key
```

And now run generate, it will generate it for you.
