### ISSUE TITLE
Implement ImageStream

### ISSUE THREAD

**Issue by cdrage** [kedgeproject/kedge#317]
After implementing DeploymentConfig, we should implement ImageStream.

However, is it possible to supply multiple image stream triggers in the same DeploymentConfig file rather than splitting it up into separate files?

```yaml
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - gitlab
      from:
        kind: ImageStreamTag
        name: gitlab:8.13.3
    type: ImageChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - redis
      from:
        kind: ImageStreamTag
        name: redis:2.6.14
    type: ImageChange
```

Would that work?

@kadel
