### ISSUE TITLE
generated  DeploymnetConfig is invalid!

### ISSUE THREAD

**Issue by kadel** [kedgeproject/kedge#352]
Generated DC by #315  is invalid. 
Selector is missing

```
name: foo
controller: deploymentconfig
containers:
  - image: quay.io/tomkral/sleeper
```
```
▶ ./kedge generate -f test.yaml | oc create -f -
The DeploymentConfig "foo" is invalid: spec.selector: Invalid value: map[string]string(nil): selector cannot be empty
```

```
▶ ./kedge generate -f test.yaml
---
apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  name: foo
spec:
  replicas: 0
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/tomkral/sleeper
        name: foo
        resources: {}
  test: false
  triggers: null
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
```

**Comment by surajssd** [comment]
I think it has to match the labels!

**Comment by kadel** [comment]
selector should match pod labels.

spec.selector = spec.template.metadata.labels

**Comment by kadel** [comment]
plus deployment config is completely missing labels. It should have autogenerated `app` label

**Comment by kadel** [comment]
Labels are not working at all. Even if I put labels to kedge they don't show up in DeploymentConfig

```
name: foo
controller: deploymentconfig
labels:
   foo: bar
containers:
  - image: quay.io/tomkral/sleeper

```

```
---
apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  name: foo
spec:
  replicas: 0
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/tomkral/sleeper
        name: foo
        resources: {}
  test: false
  triggers: null
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
```
