### ISSUE TITLE
replicas set to 0 if not specified

### ISSUE THREAD

**Issue by kadel** [kedgeproject/kedge#357]
If replicas is not set in Kedge file, the generated output shouldn't have it either.

Now it defaults to 0, which leads to a confusing situation where your containers are not started when DC id deployed.

```
name: foo
controller: deploymentconfig
containers:
  - image: quay.io/tomkral/sleeper
```

```
▶ ./kedge generate -f test.yaml
---
apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  name: foo
spec:
  replicas: 0
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/tomkral/sleeper
        name: foo
        resources: {}
  test: false
  triggers: null
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
```

replicas shouldn't be set if it's not set in Kedge file, OpenShift default will be used on the cluster side.
