### ISSUE TITLE
kedge does not filter duplicate input data

### ISSUE THREAD

**Issue by surajssd** [kedgeproject/kedge#373]
Here is a kedge file

```yaml
$ cat kedge.yml 
name: myapp
containers:
- image: myimg
```

doing conversion, it does not filter duplicate data,

```yaml
$ kedge generate -f kedge.yml -f . | grep -A 5 kind 
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: myapp
  name: myapp
--
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: myapp
  name: myapp

```

even this is not validated by kedge, I can give same file multiple times and it takes those as input.

```yaml
$ kedge generate -f kedge.yml -f kedge.yml | grep -A 5 kind 
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: myapp
  name: myapp
--
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: myapp
  name: myapp

```

I am using

```console
$ kedge version
0.3.0 (b4cc937)
```
