### ISSUE TITLE
Add support for BuildConfig and ImageStreams

### ISSUE THREAD

**Issue by kadel** [kedgeproject/kedge#385]
BuildConfig should be a new type in Kedge file.

We should do it the same way as other types. Merging `BuildConfigSpec` with `ObjectMeta` and adding it under new root level key `buildconfigs`

This will also require adding ImageStreams in the same way (merging `ImageStreamSpec with `ObjectMeta`.

full example of Kedge file with BuildConfig (using cusom s2i) and ImageStreams:
```yaml
name: guestbook-backend
controller: DeploymentConfig
containers:
  - name: backend
    image: guestbook-backend:v1
    env:
      - name: MONGODB_PASSWORD
        value: foo
      - name: MONGODB_USERNAME
        value: foo 
      - name: MONGODB_DATABASE
        value: foo
      - name: MONGODB_SERVER
        value: foo
triggers:
  - type: ConfigChange 
  - type: ImageChange 
    imageChangeParams:
      automatic: true
      containerNames:
        - backend
      from:
        kind: ImageStreamTag
        name: guestbook-backend:v1

imageStreams:
  - name: go-17-centos7
    tags:
      - name: skip-download-when-vendored
        from:
          kind: DockerImage
          name: quay.io/tomkral/go-17-centos7:skip-download-when-vendored
  - name: guestbook-backend
    tags:
      - name: v1

buildConfigs:
  - source: 
      git:
       uri: "https://github.com/kadel/guestbook-demo-backend"
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: go-17-centos7:skip-download-when-vendored 
    output:
      to:
        kind: ImageStreamTag
        name: guestbook-backend:v1
    triggers:
      - type: GitHub
        github:
          secret: secret
```

`imageStreams` definetly has to be list. But how about `buildConfigs`? Does it make sense to have multiple buildConfig if we can have only one controller in one file (or one section of the file).
It might make sense to have only one buildConfig to stay consistent with one controller.
