### ISSUE TITLE
Output generated by `kedge init` is human unfriendly :-(

### ISSUE THREAD

**Issue by kadel** [kedgeproject/kedge#397]
The file generated by `kedge init` is not friendly for new users :-(
```
./kedge init -c DeploymentConfig -i tomaskral/nonroot-nginx -p 8080 --name demo
```

currently, it looks like this
```yaml
containers:
- image: tomaskral/nonroot-nginx
controller: DeploymentConfig
name: demo
services:
- portMappings:
  - 8080
```

But something like this would look much better.

```yaml
name: demo
controller: DeploymentConfig

containers:
- image: tomaskral/nonroot-nginx

services:
- portMappings:
  - "8080"
```
