### ISSUE TITLE
Need to clarify ingresses / routes examples better.

### ISSUE THREAD

**Issue by cdrage** [kedgeproject/kedge#402]
So we've got two places for `routes` examples, and both of them are conflicting / confusing.

For example: https://github.com/kedgeproject/kedge/tree/master/docs/examples/routes

In the README.md we define routes as:

```yaml
name: webroute
host: httpd-web.192.168.42.69.nip.io
to:
  kind: Service
  name: httpd
  weight: 100
wildcardPolicy: None
```

Yet in the example it's defined as:

```yaml
name: httpd
containers:
- image: bitnami/nginx
services:
- name: httpd
  type: NodePort
  portMappings:
  - 8080:8080
routes:
- to:
    kind: Service
    name: httpd
```

Which is a tad bit confusing.

In "examples" for Ingresses and Routes, we don't actually reflect it in the spec..

From reading the README.md (https://github.com/kedgeproject/kedge/tree/master/docs/examples/routes) as well as looking at the example, wouldn't this be more effective / true?

```yaml
name: httpd                                                                                                                                                                                                                                                                       
containers:                                                                                                                                                                                                                                                                       
- image: bitnami/nginx                                                                                                                                                                                                                                                            
services:                                                                                                                                                                                                                                                                         
- name: httpd                                                                                                                                                                                                                                                                     
  type: NodePort                                                                                                                                                                                                                                                                  
  portMappings:                                                                                                                                                                                                                                                                   
  - 8080:8080                                                                                                                                                                                                                                                                     
routes:                                                                                                                                                                                                                                                                           
  name: webroute                                                                                                                                                                                                                                                                  
  host: httpd-web.192.168.42.69.nip.io                                                                                                                                                                                                                                            
  - to:                                                                                                                                                                                                                                                                           
    kind: Service                                                                                                                                                                                                                                                                 
    name: httpd                                                                                                                                                                                                                                                                   
    weight: 100                                                                                                                                                                                                                                                                   
  wildcardPolicy: None 
```

I'm just very confused on reading the spec what we're trying to implement / what kedge is doing.

Same goes within file reference: http://kedgeproject.org/file-reference/#routes

**Comment by cdrage** [comment]
Hey @containscafeine @surajssd Mind helping me explain what's going on here? Tad-confused.

**Comment by surajssd** [comment]
In README the placement of the routespec is wrong WRT kedge file httpd.yaml, I think we should explain definition of route in kedge considering `httpd.yaml` as the reference in README.

**Comment by cdrage** [comment]
@surajssd Mind doing a PR or going into more detail? Still confused.. which example is wrong?

**Comment by containscafeine** [comment]
@cdrage do we need to keep https://github.com/kedgeproject/kedge/blob/master/docs/examples/routes/README.md and https://github.com/kedgeproject/kedge/blob/master/docs/examples/routes/httpd.yml in sync.

Both the definitions are correct, README.md just shows an example which uses more fields from the RouteSpec while the httpd.yml example uses just a couple of fields from RouteSpec.

When we use -
```yaml
routes:
- to:
    kind: Service
    name: httpd
```

then it's up to the cluster to select the host since we're not specifying the field.

Neither of the examples are _wrong_, just different.

Did I understand you correctly? :(
