### ISSUE TITLE
A better way / shortcut for labels.

### ISSUE THREAD

**Issue by cdrage** [kedgeproject/kedge#432]
I'm noticing in many examples that "labels" is copied-and-pasted into multiple areas such as `services`, `secrets`, `volumeClaims`, etc.

Is there a way that we can implement the root-level `labels` key to simply apply this label to all parts of the Kedge file?

For example:
```yaml
name: redis

labels:
    app: redis

containers:
- name: redis
  image: "bitnami/redis:3.2.8-r1"
  imagePullPolicy: "IfNotPresent"
  health:
    exec:
      command:
      - redis-cli
      - ping
    initialDelaySeconds: 30
    timeoutSeconds: 5
  resources:
    requests:
      cpu: 100m
      memory: 1Gi

  # Environment variables
  env:
  - name: REDIS_PASSWORD
    valueFrom:
      secretKeyRef:
        name: redis
        key: redis-password

  volumeMounts:
  - name: redis-data
    mountPath: /bitnami/redis

services:
- name: redis
  labels:
    app: redis
  portMappings:
    - 6379:6379

volumeClaims:
- name: redis-data
  size: 10Gi

secrets:
- name: redis
  labels:
    app: redis
  data:
   redis-password: "Z2l0bGFi"
```

Instead, we'd simply remove `labels` from the sections (secrets, services) and have the root-key apply-all.

```yaml
name: redis

# This will apply to all objects (containers, volumeClaims, etc.)
labels:
    app: redis

containers:
- name: redis
  image: "bitnami/redis:3.2.8-r1"
  imagePullPolicy: "IfNotPresent"
  health:
    exec:
      command:
      - redis-cli
      - ping
    initialDelaySeconds: 30
    timeoutSeconds: 5
  resources:
    requests:
      cpu: 100m
      memory: 1Gi

  # Environment variables
  env:
  - name: REDIS_PASSWORD
    valueFrom:
      secretKeyRef:
        name: redis
        key: redis-password

  volumeMounts:
  - name: redis-data
    mountPath: /bitnami/redis

services:
- name: redis
  portMappings:
    - 6379:6379

volumeClaims:
- name: redis-data
  size: 10Gi

secrets:
- name: redis
  data:
   redis-password: "Z2l0bGFi"
```
