### ISSUE TITLE
Implement `env` shortcut

### ISSUE THREAD

**Issue by cdrage** [kedgeproject/kedge#433]
Instead of defining `name` and `value` why not this:

```yaml
        env:
          - MAX_HEAP_SIZE: 512M
          - HEAP_NEWSIZE: 100M
          - CASSANDRA_SEEDS: "cassandra-0.cassandra.default.svc.cluster.local"
```

Instead of:
```yaml
        env:
          - name: MAX_HEAP_SIZE
            value: 512M
          - name: HEAP_NEWSIZE
            value: 100M
          - name: CASSANDRA_SEEDS
            value: "cassandra-0.cassandra.default.svc.cluster.local"
```
