### ISSUE TITLE
portMappings errors with `80`, success with `80:80`

### ISSUE THREAD

**Issue by cdrage** [kedgeproject/kedge#438]
Looks to be an int / string parsing issue.

To replicate:

```yaml
name: wordpress                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                  
containers:                                                                                                                                                                                                                                                                       
  - image: wordpress:4                                                                                                                                                                                                                                                            
    health:                                                                                                                                                                                                                                                                       
      httpGet:                                                                                                                                                                                                                                                                    
        path: /                                                                                                                                                                                                                                                                   
        port: 80                                                                                                                                                                                                                                                                  
      initialDelaySeconds: 20                                                                                                                                                                                                                                                     
      timeoutSeconds: 5                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                  
    env:                                                                                                                                                                                                                                                                          
      - name: WORDPRESS_DB_NAME                                                                                                                                                                                                                                                   
        valueFrom:                                                                                                                                                                                                                                                                
          configMapKeyRef:                                                                                                                                                                                                                                                        
            name: database                                                                                                                                                                                                                                                        
            key: MYSQL_DATABASE                                                                                                                                                                                                                                                   
      - name: WORDPRESS_DB_USER                                                                                                                                                                                                                                                   
        valueFrom:                                                                                                                                                                                                                                                                
          configMapKeyRef:                                                                                                                                                                                                                                                        
            name: database                                                                                                                                                                                                                                                        
            key: MYSQL_USER                                                                                                                                                                                                                                                       
      - name: WORDPRESS_DB_PASSWORD                                                                                                                                                                                                                                               
        valueFrom:                                                                                                                                                                                                                                                                
          secretKeyRef:                                                                                                                                                                                                                                                           
            name: database-user-password                                                                                                                                                                                                                                          
            key: MYSQL_PASSWORD                                                                                                                                                                                                                                                   
      - name: WORDPRESS_DB_HOST                                                                                                                                                                                                                                                   
        value: database:3306                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                  
services:                                                                                                                                                                                                                                                                         
  - name: wordpress                                                                                                                                                                                                                                                               
    type: LoadBalancer                                                                                                                                                                                                                                                            
    portMappings:                                                                                                                                                                                                                                                                 
      - 80
```

```sh
▶ ./kedge generate -f examples/wordpress/mariadb.yaml  
unable to perform controller operations: unable to unmarshal data: could not unmarshal into internal struct: error unmarshaling JSON: json: cannot unmarshal number into Go struct field ServiceSpecMod.portMappings of type string
```

Work-around is to use:

```yaml
services:                                                                                                                                                                                                                                                                         
  - name: wordpress                                                                                                                                                                                                                                                               
    type: LoadBalancer                                                                                                                                                                                                                                                            
    portMappings:                                                                                                                                                                                                                                                                 
      - 80:80
```
