### ISSUE TITLE
Update documentation regarding separate controller constructs with PodSpec, ControllerSpec, etc.

### ISSUE THREAD

**Issue by cdrage** [kedgeproject/kedge#457]
So...

Within our documentation we've said that the "Kedge" file "extends" PodSpec.

Yet for example:

```yaml
controller: job
name: pival
containers:
- image: perl
  command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
restartPolicy: Never
parallelism: 3
```

We use "Parallelism" which is considered part of the JobSpec, not PodSpec.

Should we indicate in the documentation that depending on what controller is defined, it changes what you can define in the Kedge file?

Instead of saying that the Kedge file is simply an extension of PodSpec..
