### ISSUE TITLE
[shortcut] add imageStream shortcut to pod.spec.containers

### ISSUE THREAD

**Issue by containscafeine** [kedgeproject/kedge#460]
If something like this -
```yaml
controller: DeploymentConfig
name: webapp
containers:
- imageStream: goaserver:v1.5.2
```

could generate something like this -
```yaml
controller: DeploymentConfig
name: webapp
containers:
- image: ""
triggers:
- imageChangeParams:
    automatic: true
    containerNames:
    - webapp
    from:
      kind: ImageStreamTag
      name: goaserver:v1.5.2
  type: ImageChange
```

It would be pretty :cool:!

**Comment by cdrage** [comment]
neat :100: 

What about:

```
controller: DeploymentConfig
name: webapp
containers:
- imageStreams:
   - goaserver:v1.5.2
```

?

Would it make more sense to make it an array?

**Comment by surajssd** [comment]
https://github.com/kedgeproject/kedge/pull/445 is blocker for this issue to go forward!

**Comment by containscafeine** [comment]
@cdrage I think we should remain consistent with how `image` is defined. So, similar to -
```yaml
containers:
- image: busybox:latest
- image: centos:7
```
we can have -
```yaml
containers:
- imageStream: busybox:latest
- imageStream: centos:7
```
 WDYT?
