### ISSUE TITLE
OpenShift config creation fails: no matches for apps.openshift.io

### ISSUE THREAD

**Issue by surajssd** [kedgeproject/kedge#470]
**Problem:**

Kedge fails on creating OpenShift artifacts with error: `error: unable to recognize "STDIN": no matches for apps.openshift.io/, Kind=DeploymentConfig`

**Steps to reproduce:**

Using this kedge file:

```yaml
$ cat kedge.yml 
controller: deploymentconfig
containers:
- image: centos/httpd
name: web
services:
- portMappings:
  - 8080:80
```

Now feeding it to openshift cluster:

```console
$ kedge create -f kedge.yml 
service "web" created
error: unable to recognize "STDIN": no matches for apps.openshift.io/, Kind=DeploymentConfig
failed to execute command: failed to execute command: exit status 1
```

**Other info:**

Kedge version:

```console
$ kedge version
0.4.0 (0709fa1)
```

---

**Possible solution**:

I think we can solve this or atleast try it out, we hardcode the `apiVersion` key into the code. Right now it is automatically added here:

https://github.com/kedgeproject/kedge/blob/0709fa1e856ada2afa5ab2b7de4abcd5eedd7e13/pkg/spec/deploymentconfig.go#L106-L116
