### ISSUE TITLE
Shortcut to create a route, like endpoint is for ingress

### ISSUE THREAD

**Issue by surajssd** [kedgeproject/kedge#471]
Right now in a service if you specify a field called [`endpoint`](https://github.com/kedgeproject/kedge/tree/001f0911e87d6d6d991abf5fc70b839cdef5f9aa/docs/examples/endpoint) then an ingress is created automatically for you, similarly we need some sort of shortcut from service to OpenShift routes.

**Comment by containscafeine** [comment]
I think we should extend the `endpoint` shortcut itself.
One possible solution could be - when `endpoint: true` is set for a service, we create a route.
But yes, we will never know what to generate in case of `endpoint: example.com`, a route or an ingress.
I don't think we should have another shortcut field for generating routes.

This is somewhere a flag like `--provider openshift` will really help.

**Comment by surajssd** [comment]
As `endpoint` is implemented right now we cannot assign boolean values to endpoint, we will have to implement a type of our own to make endpoint work as string and boolean or put in double qoutes as a workaround.

About overloading the `endpoint` to do routes, kedge has no way right now to know what are we generating configs for? Yeah if we had provider we could have known what we are doing.

**Comment by containscafeine** [comment]
For this use case, I really want kedge to be provider aware and take a decision instead of adding another shortcut for similar behavior.

**Comment by kadel** [comment]
My suggestions would be to rename `endpoint` to something else, that makes it clear that it is creating Ingress and create a new shortcut for Route.

I don't think that it will be wise to create a different object with one shortcut based on the cluster type.
Ingres and Route might be similar but they have different capabilities and structures.

I believe that what type of the object will be generated should be in control of the one who is writing the Kedge file, not the one who is deploying the app.

possibilities:
- `ingressHost` / `routeHost`
- `ingressEndpoint` / `routeEndpoint`

**Comment by containscafeine** [comment]
I like `ingressHost` and `routeHost`

**Comment by surajnarwade** [comment]
Similar to `ingressEndpoint` shortcut,

```
name: database
services:
- name: database
  ports:
  - port: 3306
    ingressEndpoint: www.mycoolapp.com/admin
```

Shall we have something like this,

* `routeEndpoint` as a string

```
name: database
services:
- name: database
  ports:
  - port: 3306
    routeEndpoint: httpd-myproject.192.168.42.129.nip.io
```

* `routeEndpoint` as a bool

```
name: database
services:
- name: database
  ports:
  - port: 3306
    routeEndpoint: true
```

ping @kadel @containscafeine @cdrage
