### ISSUE TITLE
Shortcut for ConfigMaps and ImageStreams

### ISSUE THREAD

**Issue by cdrage** [kedgeproject/kedge#478]
Similar to #471 we should figure out a way to do this with ImageStreams as well as ConfigMaps.

Similar to how we currently do this with `endpoint`.

**Comment by kadel** [comment]
What we can do for ImageStreams is that we can automatically create IS for BuildConfigs.
If BuildConfig's output IS  doesn't exist Kedge will create it automatically.

If BC is defined like this:
```
---
name: mybuild
buildConfigs:
 - strategy:
    type: Binary
    sourceStrategy:
      from:
        kind: DockerImage
        name: builderImage:tag
  output:
    to:
      kind: "ImageStreamTag"
      name: "output-image:latest"
```

The following IS should be automatically created:

```
apiVersion: v1
kind: ImageStream
metadata:
  name: output-image
spec:
  tags:
  - name: latest
```

One issue that I can see with this is that we can't know if IS already exists in the cluster or not :-(
