### ISSUE TITLE
Is it possible to simplify `routes` defination

### ISSUE THREAD

**Issue by surajnarwade** [kedgeproject/kedge#489]
Can we simplify `route` defination,

Currently it looks like,

```
routes:
- name: httpd
  to:
    kind: Service
    name: httpd
```
Instead of that, something like this,

```
routes:
- name: httpd
  toService:
    name: httpd
```
Or maybe, simpler than this ?
