### ISSUE TITLE
Add support for defining `Job` controller

### ISSUE THREAD

**Issue by surajssd** [kedgeproject/kedge#52]
Right now we by default create `Deployment` as the controller, so come up with a way to define the Job controller.

Read more about job:
- Writing Job: https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/
- Job API docs: https://kubernetes.io/docs/api-reference/v1.6/#job-v1-batch
- Also look at cron job: https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/

**Comment by kadel** [comment]
Cron jobs are still alpha feature. I don't think we should add support for it until they are out of alpha.

But Jobs are in stable v1, and we should definetly support that.

**Comment by containscafeine** [comment]
Talking with @kadel, we thought that -
- JobSpec is a lot similar to DeploymentSpec, in the sense that there are top level fields and then there is PodTemplateSpec, so maybe we can treat this similar to how we reuse the PodSpec.

So, we can do something like this with jobs -

```golang
type JobSpecMod struct {
	Name                string
	api_v1.PodSpec      `json:",inline"`
	ext_v1beta1.JobSpec `json:",inline"`
}

type App struct {
	Name              string             `json:"name"`
        ...
        ...
	Jobs              []JobSpecMod       `json:"jobs,omitempty"`
}
```

This lets us defining jobs like -
```yaml
name: httpd
containers:
- image: centos/httpd
services:
  - name: httpd
    type: NodePort
    ports:
    - port: 8080
      targetPort: 80
jobs:
- name: piStuff
  activeDeadlineSeconds: 100 # part of JobSpec
  containers: # part of PodSpec
  - name: pi
    image: perl
    command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
  restartPolicy: Never
```

This also means, that defining solo jobs will be possible like -
```yaml
name: httpd
jobs:
- name: piStuff
  activeDeadlineSeconds: 100 # part of JobSpec
  containers: # part of PodSpec
  - name: pi
    image: perl
    command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
  restartPolicy: Never
```

How does this look @kedgeproject/maintainers?
Lazy consensus in effect! :yum:
