### ISSUE TITLE
Using NodePort in portMappings

### ISSUE THREAD

**Issue by cdrage** [kedgeproject/kedge#539]
So as of right now when defining portMappings, it's always `port:targetPort`. However, for some users, they may want to use `port:nodePort`.

For example, if a user were to convert:

```
services:
- name: db
  type: NodePort
 ports:
    - port: 5432
      nodePort: 32000
```

to

```
services:
- name: db
  type: NodePort
  portMappings:
    - 5432:32000
```

It would be incorrect (as portMappings is using targetPort not nodePort).

However... isn't the idea of this a bit unconventional and niche? I believe most users use loadBalancer instead of NodePort for this exact reason.

Motivation: https://github.com/fabric8-services/fabric8-wit/pull/1807

Comments @kadel @containscafeine ?
