### ISSUE TITLE
Add checks for multiple pvc with same name

### ISSUE THREAD

**Issue by surajssd** [kedgeproject/kedge#55]
Here is an example app

```yaml
name: foo 
containers:
- image: foo 
persistentVolumes:
- name: foo 
  size: 5Mi 
- name: foo 
  size: 5Mi
```

which when converted creates two `pvc`.

```yaml
$ kapp convert -f foo.yaml | grep -A 6 Persistent
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    app: foo
  name: foo
spec:
--
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    app: foo
  name: foo
spec:
```

so error out when multiple volumes with same name found

**Comment by kadel** [comment]
related to https://github.com/surajssd/kapp/issues/55

**Comment by surajssd** [comment]
@kadel #55 is this issue

**Comment by pradeepto** [comment]
LOL

**Comment by containscafeine** [comment]
Haha <3

**Comment by surajssd** [comment]
Today I checked this issue, the behavior has changed somehow of this one:

For the same input file the only output that was generated was deployment also the volumes were not populated in the pod spec.

```bash
$ kedge generate -f app.yaml 
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: foo
  name: foo
spec:
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: foo
      name: foo
    spec:
      containers:
      - image: foo
        name: foo
        resources: {}
status: {}
```

**Comment by surajssd** [comment]
oops my bad, the input file had to be changed to following:

```yaml
$ cat app.yaml 
name: foo
containers:
- image: foo
volumeClaims:
- name: foo
  size: 5Mi
- name: foo
  size: 5Mi
```
