### ISSUE TITLE
Global labels are not propagated to Service

### ISSUE THREAD

**Issue by kadel** [kedgeproject/kedge#575]
```
name: nginx
labels:
  version: 0.1.3

deployments:
- replicas: 3
  containers:
    - image: nginx:1.7.9

services:
- ports:
  - port: 80
  ```

outputed service is missing `version: 0.1.3` label:
```
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx
spec:
  ports:
  - name: nginx-80
    port: 80
    targetPort: 0
  selector:
    app: nginx
    version: 0.1.3
status:
  loadBalancer: {}
```

Other generated resources like Deployments and Ingress are correctly generated with this label
