### ISSUE TITLE
kedge create failures

### ISSUE THREAD

**Issue by ashetty1** [kedgeproject/kedge#579]
Found this regression while running some test:
```
# cat redis.yaml

name: redis

deployments:
- containers:
  - image: redis

services:
- name: redis
  portMappings:
   - 6379:6379
```

`kedge create` fails, but `kedge generate` works for the same config file:
```
# ./kedge create -f redis.yaml 
Error from server (NotFound): the server could not find the requested resource
failed to execute command: failed to execute command: exit status 1

#./kedge generate -f redis.yaml | oc create -f -
service "redis" created
deployment "redis" created

# oc version
oc v3.6.1+008f2d5
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://127.0.0.1:8443
openshift v3.6.1+008f2d5
kubernetes v1.6.1+5115d708d7

# ./kedge version
0.7.0 (b31917b)
```
