### ISSUE TITLE
Follow  Label and Annotation Recommendations

### ISSUE THREAD

**Issue by kadel** [kedgeproject/kedge#585]
https://docs.google.com/document/d/1EVy0wRJRm5nogkHl38fNKbFrhERmSL_CLNE4cxcsc_M/edit#

It would be nice if kedge uses recommendations from that document, at least for name and version (`app.kubernetes.io/name`, `app.kubernetes.io/version`)

Right now we use `app` and `appversion`, I propose chenging `appversion` to `app.kubernetes.io/version` , keeping `app` as it is and adding `app.kubernetes.io/name` that will have same value as `app`. (We are keeping `app` labels because OpenShift uses it to group objects in web console)

**Comment by kadel** [comment]
we could also add `app.kubernetes.io/deploy-manager: kedge` as a label

**Comment by cdrage** [comment]
This is as simple as adding to Kedge application labels on generation / creation, correct?

For example:

```yaml
...
apiVersion: v1
data:
  MYSQL_ROOT_PASSWORD: rootpass
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    app: database
    app.kubernetes.io/name: database
  name: database-root-password
...
```

**Comment by cdrage** [comment]
Another example (with appversion):

```yaml
metadata:
  annotations:
    appversion: 0.8.1
  creationTimestamp: null
  labels:
    app: httpd
    app.kubernetes.io/name: httpd
    app.kubernetes.io/version: 0.0.1
  name: httpd
```

**Comment by surajnarwade** [comment]
@cdrage @kadel , what's the status on community acceptance of labels/annotations proposal ?

**Comment by surajnarwade** [comment]
Some queries:

* Consider `wordpress` [examples](https://github.com/kedgeproject/kedge/tree/master/examples/wordpress)

* if I added these labels, it will be something like:

for `wordpress.yml` :

```
metadata:
  creationTimestamp: null
  labels:
    app: wordpress
    app.kubernetes.io/name: wordpress
  name: wordpress
```

For `mariadb` :

```
metadata:
  creationTimestamp: null
  labels:
    app: database
    app.kubernetes.io/name: database
  name: database
```

* It indicates, `wordpress` & `mariadb` both are different applications but it should be like, `mariadb` is component of `wordpress`.

* @cdrage @kadel @containscafeine thoughts? (I might be completely wrong here)
