### ISSUE TITLE
RFE: warn users when secret data is not base64 encoded

### ISSUE THREAD

**Issue by dustymabe** [kedgeproject/kedge#595]
It might be nice to add a feature to warn a user when secret data that is being passed in is obviously not base64 encoded. For example, if I have a secret:

```
secrets:
  - name: foo-token
    data:
      FOO_TOKEN: [[ FOO_TOKEN ]]
```

and I accidentally populated `$FOO_TOKEN` in my environment with the original token and not the base64 encoded token then a warning to help me understand that would be nice.
