### ISSUE TITLE
Getting false positive errors for validation...

### ISSUE THREAD

**Issue by cdrage** [kedgeproject/kedge#606]
With my YAML file:

```
name: gitea                                                                                                                                                                           
                                                                                                                                                                                      
labels:
  app: gitea

deployments:
- name: gitea
  replicas: 1
  livenessProbe:
    httpGet:
      path: /
      port: 3000
    initialDelaySeconds: 200
    timeoutSeconds: 1
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 10
  readinessProbe:
    httpGet:
      path: /
      port: 3000
    initialDelaySeconds: 30
    timeoutSeconds: 1
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 3

secrets:
- data:
  postgresql-user: "Z2l0ZWE="

```

I'm getting false positive validation errors...

```
▶ ./kedge generate -f examples/gitea/gitea.yaml
2018/02/28 13:17:04 The kedgefile is not valid. see errors :
livenessProbe: Additional property livenessProbe is not allowed
readinessProbe: Additional property readinessProbe is not allowed
postgresql-user: Additional property postgresql-user is not allowed
secrets.0.data: Invalid type. Expected: object, given: null
```

ping @surajnarwade @kadel @containscafeine
