### ISSUE TITLE
Default value replacement is space sensitive

### ISSUE THREAD

**Issue by surajssd** [kedgeproject/kedge#611]
Here is a sample file, here there is no space between `FOO_MODE` and `:` which works fine.

```yaml
name: foobar
labels:
  service: foobar
deployments:
- containers:
  - image: foobar:latest
    env:
    - name: FOO_MODE
      value: "[[ FOO_MODE: dev ]]"
```

This works

```yaml
$ FOO_MODE=foomode kedge generate -f testing.yaml 
---
apiVersion: extensions/v1beta1
kind: Deployment
...
      containers:
      - env:
        - name: FOO_MODE
          value: foomode
        image: foobar:latest
...
```

But when there is space between the variable and colon it doesn't work.

```yaml
name: foobar
labels:
  service: foobar
deployments:
- containers:
  - image: foobar:latest
    env:
    - name: FOO_MODE
      value: "[[ FOO_MODE : dev ]]"
```

this doesn't work

```yaml
$ FOO_MODE=fomo kedge generate -f testing.yaml 
---
apiVersion: extensions/v1beta1
kind: Deployment
...
      containers:
      - env:
        - name: FOO_MODE
          value: dev
        image: foobar:latest
...
```
the variable still has default value the override didn't work.
